### ISSUE TITLE
http://docs.anaconda.org/cli.html is broken

### ISSUE THREAD

**Issue by malev** [Anaconda-Server/docs.anaconda.org#108]
@electronwill the website is broken and it seems like you have something off on your environment when you run the deploy. We can fix this easily

**Comment by electronwill** [comment]
Sorry I didn't see the email and reply to this sooner! I haven't touched the cli.html, _cli/anaconda-client.html, or _cli/binstar-build.html pages. I haven't run a deploy script; I think Kevin does that. A few times I've heard people saying that there's some page docs.anaconda.org/foo that shows titles with no text below them, while the corresponding page docs.binstar.org/foo looks fine, and confirmed it by visiting the page, and this seems to be what's happening here. Please let me know if there's more I can do to help with this.

**Comment by electronwill** [comment]
Wait, I think I understand what you mean-- by building the pages locally with something wrong in my environment, I may have caused these pages to be blank, even if I didn't change anything in them. Let me do a local build and check to see if it's wiping out the text that way, then I'll report back here.

**Comment by electronwill** [comment]
Yes, after running 'hyde gen' and 'hyde serve -p 8080', http://localhost:8080/cli.html does show titles without text. Here's my environment:

(docsanacondaorg)docs.anaconda.org master$ conda list
# packages in environment at /Users/wwarner/anaconda/envs/docsanacondaorg:
#
commando                  0.3.2a0                   <pip>
distribute                0.6.45                   py27_1
fswrap                    0.1.1                     <pip>
hyde                      0.8.5                    py27_0
jinja2                    2.8                      py27_0
markdown                  2.3.1                    py27_0
markupsafe                0.23                     py27_0
ncurses                   5.9                           1
openssl                   1.0.1k                        1
pip                       7.1.0                    py27_1
pygments                  2.0.2                    py27_0
python                    2.7.10                        0
pyyaml                    3.11                     py27_1
readline                  6.2.5                         1
s3cmd                     1.1.0beta3               py27_0
setuptools                18.0.1                   py27_0
smartypants               1.6.0.3                   <pip>
sqlite                    3.8.4.1                       1
tk                        8.5.18                        0
typogrify                 2.0.0                     <pip>
wheel                     0.24.0                   py27_0
yaml                      0.1.6                         0
zlib                      1.2.8                         1
(docsanacondaorg)docs.anaconda.org master$

What do you think I need to change so that cli.html builds correctly?

**Comment by electronwill** [comment]
Kevin says the Continuum site seems to use jinja2 2.7.3 and have problems with 2.8, so maybe that's it?

**Comment by electronwill** [comment]
Tried with jinja2 2.7.3, still not working.

**Comment by malev** [comment]
```
conda install anaconda-client -y
hyde gen --regen
```
Try that!

**Comment by electronwill** [comment]
OK, trying...

**Comment by electronwill** [comment]
Very surprising result: There is now text for everything listed in anaconda-client.html, but still no text for the sections at the end listed in binstar-build.html .

**Comment by malev** [comment]
@electronwill that is correct, I can fix that later. but in the mean time we have something :)

**Comment by electronwill** [comment]
In general, should anyone who wants to build the docs have anaconda-client installed?

**Comment by malev** [comment]
yes, should be a requirement of the project

**Comment by electronwill** [comment]
OK, thanks. I'll add that to the readme.

**Comment by malev** [comment]
@electronwill there is a PR with an evironment file and with the readme updated
