### ISSUE TITLE
Binstar badge shows incorrect version

### ISSUE THREAD

**Issue by faph** [Anaconda-Server/docs.anaconda.org#61]
My package is currently at version `0.4.1`. Binstar badge shows `0.4.0`.

See: <https://binstar.org/OpenHydrology/autostatistical/badges>

**Comment by faph** [comment]
Package is now at `0.4.4` but showing as `0.4.3`. Is it a cache thing or is it alway one version too low?

**Comment by srossross** [comment]
Yes, this could be a cache issue. I will take a look. Thanks for bringing this to our attention.

**Comment by faph** [comment]
Thanks. It seems to be in sync again...

**Comment by marscher** [comment]
This also applies to the downloads badge (where caching seems to hurt more). It is related to this issue: 
https://github.com/github/markup/issues/224
You have to set cache (eg. expires) parameters in http headers for this to work properly.

**Comment by chrisjsewell** [comment]
I have the same issue with showing an old version (`0.4.3` instead of `0.5.0`). Also I don't know if this is related but the package version as shown on the site seems to fluctuate between the latest version and the original version, i.e. at present if I go to https://binstar.org/cjs14/pygauss and keep reloading the page, sometimes it will show `v0.2.1` and others is will show `0.5.0`.

**Comment by electronwill** [comment]
https://binstar.org/cjs14/pygauss still displays 0.2.1 some times and 0.5.0 other times. Am now merging this into the anaconda-server repo's issue describing this problem:

https://github.com/Anaconda-Server/anaconda-server/issues/314
