### ISSUE TITLE
token_gen.html miising?

### ISSUE THREAD

**Issue by goanpeca** [Anaconda-Server/docs.anaconda.org#97]
The `access tokens` link inside http://docs.anaconda.org/#PrivatePackages results in 404

Should a new page be created for this ? 

The original binstar content seems to be (http://docs.binstar.org/token_gen.html)

**Comment by malev** [comment]
@goanpeca thanks for reporting. Will fix soon

**Comment by stephenakearns** [comment]
Hi @malev - if this is a bug that needs to be fixed in Anaconda Server, would it help if this was transferred the right repo? @electronwill is going thru all the documentation issues in this repo and will transfer over any actual bugs to the main anaconda server repo?

**Comment by electronwill** [comment]
It looks like this one is a docs bug rather than an Anaconda Server bug, because the "access tokens" link points to http://docs.anaconda.org/token_gen.html which is a 404, and it looks like there should be a page there explaining access tokens, similar to http://docs.binstar.org/token_gen.html .

@malev , is that correct?

Also, is the team planning to end the system of token locked channels and use Anaconda.org usernames and passwords instead? Did the 404 happen because that process has already started?
